format_version = 4

[[images]]
width = 256
height = 256
data = [[7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 0, 0, 0, 0, 0, 3, 15, 15, 0, 0, 0, 0, 15, 0], [7, 7, 0, 0, 0, 0, 7, 7, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 15, 15, 15, 15, 15, 15, 0], [7, 0, 7, 0, 0, 7, 0, 7, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 15, 0, 15, 0], [7, 0, 0, 7, 7, 0, 0, 7, 0, 0, 0, 3, 3, 0, 0, 0, 15, 15, 0, 0, 0, 15, 0], [7, 0, 0, 7, 7, 0, 0, 7, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 15, 15, 15, 15, 15, 15, 0], [7, 0, 7, 0, 0, 7, 0, 7, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 15, 0], [7, 7, 0, 0, 0, 0, 7, 7, 3, 3, 0, 0, 0, 0, 3, 3, 0, 0, 0, 15, 15, 0], [7, 7, 7, 7, 7, 7, 7, 7, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 15, 0], [2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 13, 13, 13, 13, 13, 0], [2, 2, 0, 2, 2, 2, 2, 2, 0, 4, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 13, 13, 13, 0], [2, 0, 2, 2, 2, 2, 2, 2, 4, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 13, 0, 13, 0], [2, 0, 2, 2, 2, 0, 2, 2, 4, 0, 0, 4, 4, 0, 0, 4, 0, 0, 0, 0, 13, 0, 13, 0], [2, 2, 2, 0, 2, 0, 2, 2, 4, 4, 4, 4, 4, 0, 0, 4, 0, 13, 13, 13, 13, 0, 13, 0], [2, 2, 2, 2, 2, 2, 0, 2, 4, 0, 0, 4, 4, 0, 0, 4, 0, 0, 13, 0, 0, 0, 13, 0], [2, 0, 0, 2, 0, 0, 0, 2, 4, 4, 0, 0, 0, 0, 4, 4, 0, 0, 13, 13, 13, 0], [2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 4, 4, 4, 4, 4, 0], [0, 0, 0, 0, 0, 0, 0, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0, 10, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 10, 0, 0, 0, 10, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 10, 0], [0]]

[[images]]
width = 256
height = 256
data = [[0]]

[[images]]
width = 256
height = 256
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 0, 2, 0], [0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], [2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 0], [0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[tilemaps]]
width = 256
height = 256
imgsrc = 0
data = [[0]]

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[sounds]]
notes = []
tones = []
volumes = []
effects = []
speed = 30

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []

[[musics]]
seqs = []
